### ISSUE TITLE
MIT Licence? 

### ISSUE THREAD

**Issue by calumk** [JohnJunior/electron-desktop-capturing#1]
Can you please confirm the licence of this repo

**Comment by JohnJunior** [comment]
Hello! 

Thank you for pointing me out about the license. I added a LICENSE file.

Originally this repository was created in pair with an article for educational purposes ( https://john-tacker.medium.com/how-to-build-an-electron-desktopcapturer-screen-picker-dialog-933d004ee8e ).

So, I think the MIT license is fit for that.

**Comment by calumk** [comment]
Yes thanks, I found the repo from the original article and assumed it would be MIT due to the tutorial nature of the article, but always good to check! 

Cheers

**Comment by JohnJunior** [comment]
Cheers
